# Generated by Django 2.2.7 on 2019-11-28 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainseatchart',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Train'),
        ),
    ]
