# Generated by Django 2.2.6 on 2019-11-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='classes',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('SL', 'SL'), ('CC', 'CC')], default='SL', max_length=2),
            preserve_default=False,
        ),
    ]
