# Generated by Django 2.2.6 on 2019-11-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_train_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='classes',
            field=models.CharField(max_length=20),
        ),
    ]
