# Generated by Django 2.2.6 on 2019-11-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20191112_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainseatchart',
            name='journey_date',
            field=models.DateField(default='2019-11-12'),
            preserve_default=False,
        ),
    ]
