# Generated by Django 2.2.6 on 2019-11-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_trainseatchart_journey_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat_chart',
        ),
    ]
