# Generated by Django 2.2.7 on 2019-11-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_ticket_seat_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainseatchart',
            name='chair_car',
        ),
        migrations.AddField(
            model_name='station',
            name='assistant_manager',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='station',
            name='deputy_rpf',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='station',
            name='head_officer',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='station',
            name='manager',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='station',
            name='rpf',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='class_type',
            field=models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('SL', 'SL')], max_length=2),
        ),
    ]
